version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - 5008:5008
      - 5003:2345
    volumes:
      - .:/clean_web
    env_file: .env
    container_name: hatsu-webs
    security_opt:
      - seccomp:unconfined
    depends_on:
      - database
  api:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    security_opt:
      - seccomp:unconfined

  database:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: hatsu
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: hatsu
    container_name: hatsu_db
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - 33068:3306
    volumes:
      - hatsu_db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 5005:8080

volumes:
  hatsu_db: