definitions:
  UUID:
    description: |-
      A UUID is a 128 bit (16 byte) Universal Unique IDentifier as defined in RFC
      4122.
    items:
      format: uint8
      type: integer
    type: array
    x-go-package: github.com/google/uuid
  User:
    description: User is the database model for user.
    properties:
      id:
        $ref: '#/definitions/UUID'
    title: User represents the user for this application
    type: object
    x-go-package: clean-architecture/models
paths: {}
swagger: "2.0"
